version: 2.1
executors:
  fedora:
    docker:
      - image: registry.fedoraproject.org/fedora
    shell: /usr/bin/bash

jobs:
  build:
    executor: fedora
    steps:
      - run:
          name: Install dependencies
          command: >
            sudo dnf install --assumeyes --setopt=install_weak_deps=False
            findutils gawk gcc gettext git make
      - checkout
      - run:
          name: Build
          command: >
            make -j build

workflows:
  build:
    jobs:
      - build
